# Generated by Django 3.1.7 on 2021-03-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad_economica_establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actividad_economica_establecimiento',
            new_name='actividad_economica_est',
        ),
    ]
