# Generated by Django 3.1.7 on 2021-03-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_contribuyente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datos_cliente',
            new_name='tipo_contribuyente',
        ),
    ]
