# Generated by Django 3.1.7 on 2021-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aportante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=150)),
                ('NUMAFI', models.CharField(max_length=150)),
                ('CODDIVPOL', models.CharField(max_length=150)),
                ('RUCEMP', models.CharField(max_length=150)),
                ('CODSUC', models.CharField(max_length=150)),
                ('CODTIPEMP', models.CharField(max_length=150)),
                ('NOMEMP', models.CharField(max_length=500)),
                ('TELSUC', models.CharField(max_length=500)),
                ('DIRSUC', models.CharField(max_length=500)),
                ('FAXSUC', models.CharField(max_length=150)),
                ('APENOMAFI', models.CharField(max_length=500)),
                ('DIRAFI', models.CharField(max_length=150)),
                ('TELAFI', models.CharField(max_length=150)),
                ('CELULAR', models.CharField(max_length=150)),
                ('EMAIL', models.CharField(max_length=150)),
                ('SALARIO', models.CharField(max_length=150)),
                ('FECINGAFI', models.CharField(max_length=150)),
                ('FECSALAFI', models.CharField(max_length=150)),
                ('OCUAFI', models.CharField(max_length=150)),
                ('V19', models.CharField(max_length=150)),
                ('MES', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
