# Generated by Django 3.1.7 on 2021-03-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aportante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aportante',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aportante',
            name='state',
        ),
        migrations.RemoveField(
            model_name='aportante',
            name='updated_at',
        ),
    ]
