# Generated by Django 3.1.7 on 2021-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aportante', '0002_auto_20210318_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aportante',
            name='CODIGO',
        ),
    ]
