# Generated by Django 3.1.7 on 2021-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_cliente',
            name='CODIGO_ESTADO_CIVIL',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='CODIGO_NACIONALIDAD',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='CODIGO_PROFESION',
            field=models.CharField(max_length=30),
        ),
    ]
